"use client"
import {useEffect,useState} from "react"
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card"
import {Button} from "@/components/ui/button"
import {Input} from "@/components/ui/input"
import {Label} from "@/components/ui/label"
import {Badge} from "@/components/ui/badge"
import {Link2,ShieldCheck,Wifi,WifiOff} from "lucide-react"

export default function BrokersPage(){
 const [accountId,setAccountId]=useState(""),[token,setToken]=useState(""),[connected,setConnected]=useState(false),[account,setAccount]=useState<any>(null),[instrument,setInstrument]=useState("EUR_USD"),[units,setUnits]=useState("100"),[autoCopy,setAutoCopy]=useState(false),[message,setMessage]=useState("")
 const load=async()=>{const r=await fetch("/api/brokers/oanda/account");const d=await r.json();setConnected(d.connected);setAccount(d.account||null)}
 useEffect(()=>{load()},[])
 const connect=async()=>{setMessage("");const r=await fetch("/api/brokers/oanda/connect",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accountId,token})});const d=await r.json();if(!r.ok){setMessage(d.error||"Connection failed");return}setConnected(true);setAccount(d.account);setToken("");setMessage("OANDA Practice connected.")}
 const disconnect=async()=>{await fetch("/api/brokers/oanda/disconnect",{method:"POST"});setConnected(false);setAccount(null);setMessage("Disconnected.")}
 const order=async(side:"BUY"|"SELL")=>{setMessage("");const r=await fetch("/api/brokers/oanda/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({instrument,units:side==="BUY"?Number(units):-Number(units)})});const d=await r.json();setMessage(r.ok?"Demo order submitted.":d.error||"Order failed.")}
 return <div className="min-h-screen bg-spotify-black py-10 text-spotify-text-primary"><div className="container mx-auto max-w-6xl px-4"><p className="text-xs tracking-[0.3em] text-spotify-green">BOTFORGE · BROKER BRIDGE</p><h1 className="mt-3 font-display text-4xl font-bold">Demo accounts & copy trading</h1><p className="mt-2 max-w-3xl text-sm text-spotify-text-secondary">Connect a practice account, inspect its balance and send BotForge signals to the demo account. Live-money trading is not enabled by this page.</p>
 <div className="mt-8 grid gap-6 lg:grid-cols-2">
  <Card className="border-spotify-grey bg-spotify-dark-grey"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="text-spotify-green"/>OANDA Practice</CardTitle></CardHeader><CardContent className="space-y-4">{connected?<><div className="flex items-center justify-between"><Badge className="bg-spotify-green text-spotify-black"><Wifi className="mr-1 h-3 w-3"/>CONNECTED</Badge><Button variant="outline" onClick={disconnect}>Disconnect</Button></div><div className="grid grid-cols-2 gap-3"><div><p className="text-xs text-spotify-text-secondary">Account</p><p className="font-mono text-sm">{account?.id}</p></div><div><p className="text-xs text-spotify-text-secondary">Balance</p><p className="font-bold">{account?.balance} {account?.currency}</p></div></div></>:<><div><Label>Practice account ID</Label><Input value={accountId} onChange={e=>setAccountId(e.target.value)} className="mt-1 bg-spotify-black"/></div><div><Label>Personal API token</Label><Input type="password" value={token} onChange={e=>setToken(e.target.value)} className="mt-1 bg-spotify-black"/></div><Button onClick={connect} className="w-full bg-spotify-green text-spotify-black">Connect Practice Account</Button></>}</CardContent></Card>
  <Card className="border-spotify-grey bg-spotify-dark-grey"><CardHeader><CardTitle>Copy Trading</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label>Instrument</Label><Input value={instrument} onChange={e=>setInstrument(e.target.value.toUpperCase())} className="mt-1 bg-spotify-black"/></div><div><Label>Units</Label><Input type="number" value={units} onChange={e=>setUnits(e.target.value)} className="mt-1 bg-spotify-black"/></div><div className="flex items-center justify-between rounded-xl border border-spotify-grey p-4"><div><p className="font-medium">Auto-copy mode</p><p className="text-xs text-spotify-text-secondary">Route BotForge-generated demo signals to the connected practice account.</p></div><button onClick={()=>setAutoCopy(!autoCopy)} className={autoCopy?"h-6 w-11 rounded-full bg-spotify-green":"h-6 w-11 rounded-full bg-spotify-grey"}><span className={autoCopy?"ml-6 block h-4 w-4 rounded-full bg-black":"ml-1 block h-4 w-4 rounded-full bg-white"}/></button></div><div className="grid grid-cols-2 gap-3"><Button disabled={!connected} onClick={()=>order("BUY")} className="bg-spotify-green text-spotify-black">Copy BUY</Button><Button disabled={!connected} onClick={()=>order("SELL")} variant="outline">Copy SELL</Button></div><p className="text-[11px] text-spotify-text-secondary">Auto-copy is presented as a demo workflow; a persistent signal worker is required for unattended server-side copying.</p></CardContent></Card>
 </div>
 {message&&<div className="mt-5 rounded-xl border border-spotify-grey bg-spotify-dark-grey p-4 text-sm">{message}</div>}
 <div className="mt-8 grid gap-4 md:grid-cols-3">{[["OANDA","Practice API implemented"],["cTrader","OAuth/Open API adapter ready for integration"],["MT4 / MT5","Bridge adapter via Expert Advisor / terminal connector"]].map(([a,b])=><Card key={a} className="border-spotify-grey bg-spotify-dark-grey"><CardContent className="p-5"><Link2 className="h-5 w-5 text-spotify-green"/><h3 className="mt-3 font-semibold">{a}</h3><p className="mt-1 text-xs text-spotify-text-secondary">{b}</p></CardContent></Card>)}</div>
 </div></div>
}
